server:
  servlet:
    encoding:
      enabled: 'true'
      force: 'true'
      charset: utf-8
spring:
  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          starttls:
            enable: 'true'
          auth: 'true'
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
      debug: 'true'
    username: SECRET
    port: '587'
    default-encoding: UTF-8
    host: smtp.gmail.com
    password: SECRET
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-secret: SECRET
            redirect-uri: SECRET
            authorization-grant-type: SECRET
            client-id: SECRET
            scope: SECRET
            client-name: SECRET
            client-authentication-method: POST
        provider:
          kakao:
            user-name-attribute: SECRET
            user-info-uri: SECRET
            authorization-uri: SECRET
            token-uri: SECRET
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    password: SECRET
    username: SECRET
    url: SECRET
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
cloud:
  aws:
    s3:
      bucket: SECRET
    region:
      static: SECRET
    credentials:
      accessKey: SECRET
      secretKey: SECRET
    stack:
      auto: 'false'
jwt:
  secret: SECRET
